'use client';

import { motion } from 'framer-motion';
import { ScrollText, Gavel, Copyright, UserCheck, AlertTriangle } from 'lucide-react';
import { Spotlight } from '@/components/ui/spotlight';

export default function TermsAndConditions() {
    return (
        <div className="min-h-screen bg-black overflow-x-hidden">
            <Spotlight className="-top-40 left-0 md:left-60 md:-top-20" fill="white" />

            <div className="max-w-4xl mx-auto px-4 py-20 relative z-10">
                <motion.div
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.5 }}
                    className="space-y-8"
                >
                    <div className="text-center space-y-4 mb-12">
                        <div className="inline-flex items-center justify-center p-4 rounded-full bg-primary/10 text-primary mb-4 ring-1 ring-primary/20">
                            <ScrollText className="h-8 w-8" />
                        </div>
                        <h1 className="text-4xl font-bold tracking-tight md:text-5xl bg-clip-text text-transparent bg-gradient-to-b from-white to-white/50">
                            Terms and Conditions
                        </h1>
                        <p className="text-lg text-muted-foreground">
                            The rules of the game. Fair, transparent, and built for trust.
                        </p>
                    </div>

                    <div className="space-y-6">
                        <TermSection
                            icon={<ScrollText className="h-5 w-5 text-blue-400" />}
                            title="1. Introduction"
                            content="Welcome to CodeGenesis. By accessing our website and using our AI-powered software architecture services, you agree to be bound by these Terms and Conditions."
                        />

                        <TermSection
                            icon={<Gavel className="h-5 w-5 text-purple-400" />}
                            title="2. Use of Service"
                            content='CodeGenesis provides AI-assisted code generation and architecture planning. You agree to use this service responsibly and not for any malicious purposes. The generated code is provided "as is" and we are not liable for any errors or security vulnerabilities in the generated output.'
                        />

                        <TermSection
                            icon={<Copyright className="h-5 w-5 text-green-400" />}
                            title="3. Intellectual Property"
                            content="The code generated by CodeGenesis for your specific projects belongs to you. However, the underlying AI models, algorithms, and platform infrastructure remain the property of CodeGenesis and its developers, Aditya Shenvi and Sneha Sah."
                        />

                        <TermSection
                            icon={<UserCheck className="h-5 w-5 text-orange-400" />}
                            title="4. User Data & Privacy"
                            content="We respect your privacy. Your project data and prompts are processed to provide the service. We do not sell your personal code or proprietary logic to third parties."
                        />

                        <TermSection
                            icon={<AlertTriangle className="h-5 w-5 text-red-400" />}
                            title="5. Limitation of Liability"
                            content="CodeGenesis is an assistive tool. It does not replace human review. We are not responsible for any damages or losses resulting from the use of code generated by our platform."
                        />

                        <div className="p-6 rounded-2xl bg-white/5 border border-white/10 text-sm text-muted-foreground flex justify-between items-center mt-8">
                            <div>
                                <p>Last updated: December 2025</p>
                                <p className="mt-1">Contact: support@codegenesis.ai</p>
                            </div>
                            <ScrollText className="h-10 w-10 text-white/10" />
                        </div>
                    </div>
                </motion.div>
            </div>
        </div>
    );
}

function TermSection({ icon, title, content }: { icon: React.ReactNode, title: string, content: string }) {
    return (
        <motion.div
            initial={{ opacity: 0, y: 10 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="p-6 rounded-2xl bg-white/5 border border-white/10 hover:border-primary/50 transition-colors"
        >
            <div className="flex items-center gap-3 mb-4">
                <div className="p-2 rounded-lg bg-black/50 border border-white/10">
                    {icon}
                </div>
                <h2 className="text-xl font-semibold text-white">{title}</h2>
            </div>
            <div className="text-muted-foreground leading-relaxed pl-12">
                {content}
            </div>
        </motion.div>
    )
}
